import { Employee } from "./types/employee";

export const employees: Employee[] = [
  {
    id: 1,
    firstName: "Özgür",
    lastName: "Çiriş",
    title: "Frontend Developer",
    voteCount: 10,
    image: "https://picsum.photos/id/1/200/300",
    email: "ozgur.ciris@example.com",
    phone: "+1234567890",
    address: "123 Main St, Cityville, Country",
  },
  {
    id: 2,
    firstName: "Selin",
    lastName: "Kaya",
    title: "Backend Developer",
    voteCount: 8,
    image: "https://picsum.photos/id/1/200/300",
    email: "selin.kaya@example.com",
    phone: "+9876543210",
    address: "456 Oak St, Townsville, Country",
  },
  {
    id: 3,
    firstName: "Mert",
    lastName: "Demir",
    title: "Full Stack Developer",
    voteCount: 7,
    image: "https://picsum.photos/id/1/200/300",
    email: "mert.demir@example.com",
    phone: "+1122334455",
    address: "789 Pine St, Villageland, Country",
  },
  {
    id: 4,
    firstName: "Aslı",
    lastName: "Yılmaz",
    title: "UI/UX Designer",
    voteCount: 6,
    image: "https://picsum.photos/id/1/200/300",
    email: "asli.yilmaz@example.com",
    phone: "+9988776655",
    address: "101 Cedar St, Hamletville, Country",
  },
  {
    id: 5,
    firstName: "Emre",
    lastName: "Aksoy",
    title: "Data Scientist",
    voteCount: 5,
    image: "https://picsum.photos/id/1/200/300",
    email: "emre.aksoy@example.com",
    phone: "+3344556677",
    address: "202 Elm St, Riverside, Country",
  },
  {
    id: 6,
    firstName: "Gizem",
    lastName: "Ergün",
    title: "Frontend Developer",
    voteCount: 0,
    image: "https://picsum.photos/id/1/200/300",
    email: "gizem.ergun@example.com",
    phone: "+1122334455",
    address: "303 Maple St, Lakeside, Country",
  },
  {
    id: 7,
    firstName: "Efe",
    lastName: "Kurt",
    title: "Backend Developer",
    voteCount: 0,
    image: "https://picsum.photos/id/1/200/300",
    email: "efe.kurt@example.com",
    phone: "+9988776655",
    address: "404 Birch St, Mountainside, Country",
  },
  {
    id: 8,
    firstName: "Aylin",
    lastName: "Şahin",
    title: "Full Stack Developer",
    voteCount: 0,
    image: "https://picsum.photos/id/1/200/300",
    email: "aylin.sahin@example.com",
    phone: "+3344556677",
    address: "505 Pine St, Seaside, Country",
  },
];
